export const captions: string[] = [
    "绝不用 Java。",
    "绝不用 Scala。",
    "绝不用 Haskell。",
    "绝不用 OCaml。",
    "绝不用 Coq。",
    "绝不用 Agda。",
    "绝不用 Lean。",
    "绝不用 Arend。",
    "绝不用 Koka。",
    "绝不用 Isabelle。",
    "绝不用 PHP。",
    "绝不用 Clojure。",
    "绝不用 Rust。",
    "绝不用 C。",
    "绝不用 C++。",
    "绝不用 C#。",
    "绝不用 F#。",
    "绝不用 F*。",
    "绝不用 Python。",
    "绝不用 Mojo。",
    "绝不用 Julia。",
    "绝不用 Ruby。",
    "绝不用 Groovy。",
    "绝不用 COBOL。",
    "绝不用 Dart。",
    "绝不用 Swift。",
    "绝不用 JavaScript。",
    "绝不用 TypeScript。",
    "绝不用 ReScript。",
    "绝不用 PureScript。",
    "绝不用 Lua。",
    "绝不用 Objective-C。",
    "绝不用 Visual Basic。",
    "绝不用 Perl。",
    "绝不用 Elixir。",
    "绝不用 Erlang。",
    "绝不用 Lisp。",
    "绝不用 Racket。",
    "绝不用 Chez Scheme。",
    "绝不用 Golang。",
    "绝不玩原神。",
    "绝不玩王者荣耀。",
    "绝不玩明日方舟。",
    "绝不玩星穹轨道。"
];

export default function getRandomCaption(): string {
    return captions[Math.floor(Math.random() * captions.length)];
}